{
 "title": "Kafka Connect",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Connectors on Worker",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_count{job='kafkaConnect'}"
    }
   ]
  },
  {
   "title": "Connector Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_status{job='kafkaConnect'}",
     "legendFormat": "{{connector}}: {{status}}"
    }
   ]
  },
  {
   "title": "Number of Tasks on Worker",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_connect_worker_task_count{job='kafkaConnect'}"
    }
   ]
  },
  {
   "title": "Number of Running Tasks Per Connector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_worker_connector_running_task_count{job='kafkaConnect'})"
    }
   ]
  }
 ]
}