{
 "title": "Kafka02",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "UnderReplicatedPartitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.\nNormal value 0.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable. Alert if value is greater than 0.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "UnderMinIsrPartitionCount",
   "type": "singlestat",
   "description": "Number of partitions whose in-sync replicas count is less than minIsr.\nNormal value 0.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underminisrpartitioncount{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "AtMinIsrPartitionCount",
   "type": "singlestat",
   "description": "Normal value 0",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicamanager_atminisrpartitioncount{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "BytesInPerMin Per Topic",
   "type": "graph",
   "description": "Byte in rate from clients",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Bytes/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka02\",topic!=\"\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total BytesInPerMin",
   "type": "singlestat",
   "description": "Byte in rate from clients",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka02\",topic!=\"\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "BytesOutPerMin Per Topic",
   "type": "graph",
   "description": "Byte out rate to clients",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Bytes/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka02\",topic!=\"\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total BytesOutPerMin",
   "type": "singlestat",
   "description": "Byte out rate to clients",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka02\",topic!=\"\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "MessagesInPerMin Per Topic",
   "type": "graph",
   "description": "Message in rate",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Messages/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka02\",topic!=\"\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total MessagesInPerMin",
   "type": "singlestat",
   "description": "Byte out rate to clients",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka02\",topic!=\"\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "RequestsPerMin Per Request",
   "type": "graph",
   "description": "Request rate",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Requests/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_network_requestmetrics_requests_total{job=\"kafka02\"}[1m])",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total RequestsPerMin",
   "type": "singlestat",
   "description": "Byte out rate to clients",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kafka_network_requestmetrics_requests_total{job=\"kafka02\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "TotalFetchRequestsPerMin",
   "type": "graph",
   "description": "Fetch request rate",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Requests/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_totalfetchrequests_total{job=\"kafka02\",topic=\"\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TotalProduceRequestsPerMin",
   "type": "graph",
   "description": "Produce request rate",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Requests/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"kafka02\",topic=\"\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FailedFetchRequestsPerMin",
   "type": "graph",
   "description": "Fetch request rate for requests that failed.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Requests/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=\"kafka02\",topic=\"\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FailedProduceRequestsPerMin",
   "type": "graph",
   "description": "Produce request rate for requests that failed.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Requests/min" }
   ],
   "targets": [
    {
     "expr": "delta(kafka_server_brokertopicmetrics_failedproducerequests_total{job=\"kafka02\",topic=\"\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "LeaderElectionRateAndTimeMs",
   "type": "graph",
   "description": "Leader election rate and latency.\nnon-zero when there are broker failures.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_controllerstats_leaderelectionrateandtimems{job=\"kafka02\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "UncleanLeaderElectionsPerSec",
   "type": "graph",
   "description": "Unclean leader election rate.\nNormal value 0.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_controllerstats_uncleanleaderelectionspersec{job=\"kafka02\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "PartitionCount",
   "type": "singlestat",
   "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "LeaderCount",
   "type": "singlestat",
   "description": "Number of leaders on this broker. This should be mostly even across all brokers. If not, set auto.leader.rebalance.enable to true on all brokers in the cluster.",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "MaxLag",
   "type": "singlestat",
   "description": "Maximum lag in messages between the follower and leader replicas. This is controlled by the replica.lag.max.messages config.\nlag should be proportional to the maximum batch size of a produce request.",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "IsrShrinksPerSec",
   "type": "singlestat",
   "description": "If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_isrshrinks_total{job=\"kafka02\"}[5m])"
    }
   ]
  },
  {
   "title": "IsrExpandsPerSec",
   "type": "singlestat",
   "description": "When a broker is brought up after a failure, it starts catching up by reading from the leader. Once it is caught up, it gets added back to the ISR.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 49 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_isrexpands_total{job=\"kafka02\"}[5m])"
    }
   ]
  },
  {
   "title": "RequestQueueSize",
   "type": "graph",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize{job=\"kafka02\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "AVG TotalTimeMs",
   "type": "graph",
   "description": "Total time in ms to serve the specified request\nbroken into queue, local, remote and response send time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(delta(kafka_network_requestmetrics_totaltimems{job=\"kafka02\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "AvgPerMin RequestQueueTimeMs",
   "type": "gauge",
   "description": "Time the request waits in the request queue",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "avg(delta(kafka_network_requestmetrics_requestqueuetimems{job=\"kafka02\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "AvgPerMin LocalTimeMs",
   "type": "gauge",
   "description": "Time the request is processed at the leader",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 70 },
   "targets": [
    {
     "expr": "avg(delta(kafka_network_requestmetrics_localtimems{job=\"kafka02\"}[1m]))"
    }
   ]
  },
  {
   "title": "AvgPerMin RemoteTimeMs",
   "type": "gauge",
   "description": "Time the request waits for the follower. This is non-zero for produce requests when acks=all",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 70 },
   "targets": [
    {
     "expr": "avg(delta(kafka_network_requestmetrics_remotetimems{job=\"kafka02\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "AvgPerMin ResponseQueueTimeMs",
   "type": "gauge",
   "description": "Time the request waits in the response queue",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 70 },
   "targets": [
    {
     "expr": "avg(delta(kafka_network_requestmetrics_responsequeuetimems{job=\"kafka02\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "AvgPerMin ResponseSendTimeMs",
   "type": "gauge",
   "description": "Time to send the response",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 70 },
   "targets": [
    {
     "expr": "avg(delta(kafka_network_requestmetrics_responsesendtimems{job=\"kafka02\"}[1m]))",
     "legendFormat": "{{kafka02}}"
    }
   ]
  },
  {
   "title": "FetcherLagMetrics",
   "type": "graph",
   "description": "Lag in number of messages per follower replica. This is useful to know if the replica is slow or has stopped replicating from the leader.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_fetcherlagmetrics_consumerlag{job=\"kafka02\"}",
     "legendFormat": "{{clientId}}\\{{topic}}\\{{partition}}"
    }
   ]
  },
  {
   "title": "Producer PurgatorySize",
   "type": "graph",
   "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_delayedoperation_produce{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "Fetcher PurgatorySize",
   "type": "graph",
   "description": "Number of requests waiting in the fetch purgatory. This is high if consumers use a large value for fetch.wait.max.ms",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_delayedoperation_fetch{job=\"kafka02\"}"
    }
   ]
  }
 ]
}