{
 "title": "Kafka Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Brokers",
   "type": "singlestat",
   "description": "Number of brokers in cluster",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_brokers{job=\"kafka_exporter\"}"
    }
   ]
  },
  {
   "title": "ActiveControllerCount kafka01",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka01\"}"
    }
   ]
  },
  {
   "title": "ActiveControllerCount kafka02",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka02\"}"
    }
   ]
  },
  {
   "title": "ActiveControllerCount kafka03",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka03\"}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{job=\"kafka_exporter\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "CPU Usage Kafka01",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka01\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used Kafka01",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka01\"})"
    }
   ]
  },
  {
   "title": "Time spent in GC Kafka01",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka01\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage kafka02",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka02\"}[1m])"
    }
   ]
  },
  {
   "title": "JVM Memory Used kafka02",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka02\"})"
    }
   ]
  },
  {
   "title": "Time spent in GC kafka02",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka02\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage kafka03",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka03\"}[1m])"
    }
   ]
  },
  {
   "title": "JVM Memory Used kafka03",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka03\"})"
    }
   ]
  },
  {
   "title": "Time spent in GC kafka03",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka03\"}[5m]))"
    }
   ]
  }
 ]
}