{
 "title": "Zookeeper Cluster",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "description": "Quorum size formed by zookeeper nodes",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(zookeeper_QuorumSize)" }
   ]
  },
  {
   "title": "ElectionTimeTaken",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "zookeeper_ElectionTimeTaken", "legendFormat": "{{job}}: {{memberType}}" }
   ]
  },
  {
   "title": "NumAliveConnections",
   "type": "graph",
   "description": "Should be not close to maxClientCnxns",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_NumAliveConnections", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "MaxClientCnxns",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(zookeeper_MaxClientCnxnsPerHost)"
    }
   ]
  },
  {
   "title": "AvgRequestLatency",
   "type": "graph",
   "description": "Target below 10ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "zookeeper_AvgRequestLatency", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "OutstandingRequests",
   "type": "gauge",
   "description": "Should be below 10 in general",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "zookeeper_OutstandingRequests", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "HeapMemoryUsage",
   "type": "graph",
   "description": "Should be relatively flat and well below max heap size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"zookeeper01\", area=\"heap\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "jvm_memory_bytes_used{job=\"zookeeper02\", area=\"heap\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "jvm_memory_bytes_used{job=\"zookeeper03\", area=\"heap\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "avg(jvm_memory_bytes_max{ area=\"heap\"})",
     "legendFormat": "MaxHeapMemory"
    }
   ]
  }
 ]
}